# -*- coding: utf-8 -*-
"""Topic agile Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ya-ltn1z7X8vcPjOKxKy33Qw07nOZTGJ
"""

import os
import pandas as pd
import streamlit as st
import trafilatura
from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel
from typing import Literal

load_dotenv()

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

CATEGORIES = [
    "User Story Management",
    "Backlog Management",
    "Estimation",
    "Task Management",
    "Dependency & Resource Management",
    "Sprint & Project Monitoring",
    "Agile Collaboration Support",
    "Decision Support & Risk Management",
    "Other / To be classified later",
]


class ClassificationResult(BaseModel):
    category: Literal[
        "User Story Management",
        "Backlog Management",
        "Estimation",
        "Task Management",
        "Dependency & Resource Management",
        "Sprint & Project Monitoring",
        "Agile Collaboration Support",
        "Decision Support & Risk Management",
        "Other / To be classified later",
    ]
    subcategory: str
    confidence: Literal["High", "Medium", "Low"]
    reason: str
    evidence: str


SYSTEM_PROMPT = """
You are an expert reviewer conducting a multivocal literature review on
LLM-based multi-agent systems for Agile Project Management.

Your task is to classify each source into exactly one category.

Use the following taxonomy:

1. User Story Management:
   refinement, quality improvement, prioritization of user stories.

2. Backlog Management:
   backlog grooming, backlog organization, backlog prioritization.

3. Estimation:
   user story estimation, story point estimation, effort estimation,
   task effort/time estimation, complexity estimation.

4. Task Management:
   task decomposition, task planning, task scheduling, task prioritization.

5. Dependency & Resource Management:
   dependency detection, blocker identification, assignee allocation,
   resource allocation, role allocation, capability matching.

6. Sprint & Project Monitoring:
   sprint planning, progress tracking, issue tracking, status reporting.

7. Agile Collaboration Support:
   meeting assistance, scrum support, daily scrum, retrospective support,
   collaboration assistance.

8. Decision Support & Risk Management:
   risk prediction, recommendations, quality support, managerial or technical decision support.

9. Other / To be classified later:
   use only if the source does not clearly fit any of the above categories.

Important rules:
- Choose only one main category.
- Do not classify general project management unless it is clearly related to Agile software project management.
- If the source is about user story generation only, classify it as User Story Management only if it also includes refinement, prioritization, or quality improvement.
- If the source is about breaking user stories or requirements into executable tasks, classify it as Task Management.
- If the source is mainly about story points, effort, time, or complexity, classify it as Estimation.
- If uncertain, use "Other / To be classified later" and explain why.
- Keep the reason short and evidence directly grounded in the text.
"""


def classify_text(title: str, text: str) -> ClassificationResult:
    user_prompt = f"""
Source title:
{title}

Source text:
{text[:12000]}

Classify this source according to the taxonomy.
"""

    response = client.responses.parse(
        model="gpt-4o-mini",
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        text_format=ClassificationResult,
    )

    return response.output_parsed


def extract_text_from_url(url: str) -> str:
    downloaded = trafilatura.fetch_url(url)
    if downloaded is None:
        return ""

    extracted = trafilatura.extract(downloaded, include_comments=False, include_tables=False)
    return extracted or ""


st.set_page_config(page_title="Agile PM Source Classifier", layout="wide")

st.title("Agile Project Management Source Classifier")
st.write("Classify papers and grey literature into Agile Project Management categories.")

mode = st.radio(
    "Select input type:",
    ["Paper: Title + Abstract", "Grey Literature: URL", "Batch: Excel/CSV"],
)

if mode == "Paper: Title + Abstract":
    title = st.text_input("Paper title")
    abstract = st.text_area("Abstract", height=250)

    if st.button("Classify"):
        if not title or not abstract:
            st.warning("Please enter both title and abstract.")
        else:
            result = classify_text(title, abstract)

            st.subheader("Classification Result")
            st.write("**Category:**", result.category)
            st.write("**Subcategory:**", result.subcategory)
            st.write("**Confidence:**", result.confidence)
            st.write("**Reason:**", result.reason)
            st.write("**Evidence:**", result.evidence)


elif mode == "Grey Literature: URL":
    url = st.text_input("Grey literature URL")

    if st.button("Read URL and Classify"):
        if not url:
            st.warning("Please enter a URL.")
        else:
            with st.spinner("Extracting text from the webpage..."):
                text = extract_text_from_url(url)

            if not text:
                st.error("Could not extract readable text from this URL.")
            else:
                st.success("Text extracted successfully.")
                with st.expander("Preview extracted text"):
                    st.write(text[:3000])

                result = classify_text(url, text)

                st.subheader("Classification Result")
                st.write("**Category:**", result.category)
                st.write("**Subcategory:**", result.subcategory)
                st.write("**Confidence:**", result.confidence)
                st.write("**Reason:**", result.reason)
                st.write("**Evidence:**", result.evidence)


elif mode == "Batch: Excel/CSV":
    uploaded_file = st.file_uploader("Upload Excel or CSV", type=["xlsx", "csv"])

    if uploaded_file:
        if uploaded_file.name.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_excel(uploaded_file)

        st.write("Preview:")
        st.dataframe(df.head())

        st.info(
            "Expected columns for papers: title, abstract. "
            "Expected column for grey literature: url."
        )

        if st.button("Classify all rows"):
            results = []

            for _, row in df.iterrows():
                title = str(row.get("title", ""))
                abstract = str(row.get("abstract", ""))
                url = str(row.get("url", ""))

                if url and url.lower() != "nan":
                    text = extract_text_from_url(url)
                    source_title = url
                else:
                    text = abstract
                    source_title = title

                if not text or text.lower() == "nan":
                    results.append({
                        "title": title,
                        "url": url,
                        "category": "Other / To be classified later",
                        "subcategory": "",
                        "confidence": "Low",
                        "reason": "No usable text was available.",
                        "evidence": "",
                    })
                    continue

                try:
                    result = classify_text(source_title, text)

                    results.append({
                        "title": title,
                        "url": url,
                        "category": result.category,
                        "subcategory": result.subcategory,
                        "confidence": result.confidence,
                        "reason": result.reason,
                        "evidence": result.evidence,
                    })

                except Exception as e:
                    results.append({
                        "title": title,
                        "url": url,
                        "category": "Other / To be classified later",
                        "subcategory": "",
                        "confidence": "Low",
                        "reason": f"Classification failed: {e}",
                        "evidence": "",
                    })

            result_df = pd.DataFrame(results)
            st.subheader("Results")
            st.dataframe(result_df)

            csv = result_df.to_csv(index=False).encode("utf-8")
            st.download_button(
                "Download results as CSV",
                data=csv,
                file_name="agile_pm_classification_results.csv",
                mime="text/csv",
            )